### ISSUE TITLE
Mad weird

### ISSUE THREAD

**Issue by MochaDEBUG** [sprxsh/serenity-panel#12]
Ok so, DONT DOWNLOAD THIS MY WINDOWS SECURITY SAID ITS MALWARE ITS SEVERE IT SAID IT PROVIDES BACKDOOR ACCESS ON YOUR COMPUTER
![Screenshot 2024-07-21 213151](https://github.com/user-attachments/assets/f9c284ab-49f8-4edd-9d3f-43df6f0fc089)

**Comment by thebashfile** [comment]
This is a false positive by the obfuscation process. Source code is public and tool has been patched for years.
