### ISSUE TITLE
Tool Doesn't Work

### ISSUE THREAD

**Issue by Wan2uu** [sprxsh/serenity-panel#6]
Nothing works and I keep getting windows 10 defender telling me that Win32 Backdoor is trying to access files. I get trying to make a XBL Tool requires some admin permissions but if you're going to make a tool for mal intent and fester it with a trojan. at least do a better job at hiding it. I just Rev-Eng. the application and removed anything that was identified as a security issue. still works the same as before. terrible.

**Comment by thebashfile** [comment]
This is quite literally false. I use a custom obfusctor and due to the methods used it shows as malicious. If you believe it to be a Trojan simply don’t open it. You didn’t reverse engineer anything lmao.
